### ISSUE TITLE
replace type codemods do not codemod return types

### ISSUE THREAD

**Issue by eps1lon** [eps1lon/types-react-codemod#374]
From bluesky/social-app:

```ts
const NavItem: React.FC<{
  children: (props: {isActive: boolean}) => React.ReactChild
  href: string
  routeName: string
}> = ({children, href, routeName}) => {
 // ...
}
```

`React.ReactChild` should've been replace.

**Comment by eps1lon** [comment]
Actually a parser bug: 
```
src/view/shell/bottom-bar/BottomBarWeb.tsx Transformation error (Unexpected token, expected "=>" (193:41))
SyntaxError: Unexpected token, expected "=>" (193:41)
    at constructor (**/types-react-codemod/node_modules/@babel/parser/lib/index.js:353:19)
    at TypeScriptParserMixin.raise (**/types-react-codemod/node_modules/@babel/parser/lib/index.js:3277:19)
    at TypeScriptParserMixin.unexpected (**/types-react-codemod/node_modules/@babel/parser/lib/index.js:3297:16)
    at TypeScriptParserMixin.expect (**/types-react-codemod/node_modules/@babel/parser/lib/index.js:3601:28)
    at **/types-react-codemod/node_modules/@babel/parser/lib/index.js:8322:12
    at TypeScriptParserMixin.tsInType (**/types-react-codemod/node_modules/@babel/parser/lib/index.js:8509:14)
    at TypeScriptParserMixin.tsParseTypeOrTypePredicateAnnotation (**/types-react-codemod/node_modules/@babel/parser/lib/index.js:8320:17)
    at TypeScriptParserMixin.tsFillSignature (**/types-react-codemod/node_modules/@babel/parser/lib/index.js:7804:39)
    at **/types-react-codemod/node_modules/@babel/parser/lib/index.js:8098:54
    at TypeScriptParserMixin.tsInAllowConditionalTypesContext (**/types-react-codemod/node_modules/@babel/parser/lib/index.js:8527:14)
```
